"""bend_edge — atomic. Round bend along a straight edge.

Splits a flat sheet at a straight, axis-aligned edge on the top face and
rotates one half of the sheet about a bend axis offset from the edge by
`radius_mm`. The connecting region is a toroidal sector built by revolving
the bend cross-section.

Geometry (canonical case: edge parallel to Y, bending the +X half upward):
    - bend axis is parallel to +Y at (x_bend, t + radius), where t = sheet
      thickness. Axis sits above the top surface by `radius_mm`.
    - inner bend surface = the original top surface (z = t).
    - outer bend surface = the original bottom surface (z = 0), with effective
      bend radius radius + t.
    - the "keep" half stays unchanged; the "bend" half is rotated about the
      bend axis by the bend angle.
    - the arc region (between them) is a toroidal sector — generated by
      revolving the bend cross-section (rectangle in the YZ plane at
      x = x_bend, height t, width = edge length) about the bend axis.

`bend_side` selects which half of the sheet is rotated (+X, -X, +Y, -Y).
Positive `angle_deg` always means "bend upward" (rotated half ends up with
+Z component). Negative angle bends downward.
"""
from __future__ import annotations

import math
from typing import Any, Literal

from pydantic import BaseModel, Field

from phone_designer.skills._history import EntityHistoryMap, HistoryRule
from phone_designer.skills._post_conditions import PostCondition
from phone_designer.skills._registry import skill
from phone_designer.skills._selectors import SelectorRef
from phone_designer.skills._spec import SkillBase, SkillResult


def _shape_bbox(shape) -> tuple[float, float, float, float, float, float]:
    """Return (xmin, ymin, zmin, xmax, ymax, zmax) bbox for an OCCT shape."""
    from OCP.Bnd import Bnd_Box
    from OCP.BRepBndLib import BRepBndLib

    bb = Bnd_Box()
    BRepBndLib.Add_s(shape, bb, True)
    xmin, ymin, zmin, xmax, ymax, zmax = bb.Get()
    return xmin, ymin, zmin, xmax, ymax, zmax


def _resolve_bend_edge(shape, selector):
    """Resolve the selector and return one straight, axis-aligned edge.

    Falls back to picking the unique matched edge; if multiple are matched we
    pick the one closest to the top face (highest z midpoint). Raises if no
    edge is matched.
    """
    from OCP.BRep import BRep_Tool
    from OCP.TopExp import TopExp

    from phone_designer.skills._resolvers import resolve_edges

    edges = resolve_edges(shape, selector)
    if not edges:
        raise RuntimeError(
            f"bend_edge: edge selector matched 0 edges: "
            f"{selector.model_dump() if hasattr(selector, 'model_dump') else selector}"
        )

    def _z_mid(e):
        v1 = TopExp.FirstVertex_s(e)
        v2 = TopExp.LastVertex_s(e)
        p1 = BRep_Tool.Pnt_s(v1)
        p2 = BRep_Tool.Pnt_s(v2)
        return (p1.Z() + p2.Z()) / 2.0

    # Prefer the edge with highest z midpoint (the top edge of the sheet).
    edges_sorted = sorted(edges, key=_z_mid, reverse=True)
    return edges_sorted[0]


def _edge_geom(edge):
    """Return (axis: 'X'|'Y'|'Z', mid_point, length, endpoints)."""
    from OCP.BRep import BRep_Tool
    from OCP.TopExp import TopExp

    v1 = TopExp.FirstVertex_s(edge)
    v2 = TopExp.LastVertex_s(edge)
    p1 = BRep_Tool.Pnt_s(v1)
    p2 = BRep_Tool.Pnt_s(v2)
    dx = abs(p1.X() - p2.X())
    dy = abs(p1.Y() - p2.Y())
    dz = abs(p1.Z() - p2.Z())
    EPS = 1e-6
    if dx > EPS and dy < EPS and dz < EPS:
        axis = "X"
        length = dx
    elif dy > EPS and dx < EPS and dz < EPS:
        axis = "Y"
        length = dy
    elif dz > EPS and dx < EPS and dy < EPS:
        axis = "Z"
        length = dz
    else:
        raise RuntimeError(
            f"bend_edge: matched edge is not axis-aligned (delta=({dx:.3f},{dy:.3f},{dz:.3f}))"
        )
    mid = ((p1.X() + p2.X()) / 2.0, (p1.Y() + p2.Y()) / 2.0, (p1.Z() + p2.Z()) / 2.0)
    return axis, mid, length, ((p1.X(), p1.Y(), p1.Z()), (p2.X(), p2.Y(), p2.Z()))


def _make_box(corner: tuple[float, float, float],
              dx: float, dy: float, dz: float):
    """Raw axis-aligned box from a corner with positive extents."""
    from OCP.BRepPrimAPI import BRepPrimAPI_MakeBox
    from OCP.gp import gp_Pnt

    if dx <= 0 or dy <= 0 or dz <= 0:
        raise RuntimeError(
            f"bend_edge: degenerate box extent ({dx},{dy},{dz})"
        )
    mk = BRepPrimAPI_MakeBox(gp_Pnt(*corner), dx, dy, dz)
    mk.Build()
    if not mk.IsDone():
        raise RuntimeError("bend_edge: BRepPrimAPI_MakeBox failed")
    return mk.Shape()


def _rotate_shape(shape, axis_origin: tuple[float, float, float],
                  axis_direction: tuple[float, float, float], angle_rad: float):
    from OCP.BRepBuilderAPI import BRepBuilderAPI_Transform
    from OCP.gp import gp_Ax1, gp_Dir, gp_Pnt, gp_Trsf

    trsf = gp_Trsf()
    trsf.SetRotation(
        gp_Ax1(gp_Pnt(*axis_origin), gp_Dir(*axis_direction)),
        angle_rad,
    )
    xf = BRepBuilderAPI_Transform(shape, trsf, True)
    xf.Build()
    if not xf.IsDone():
        raise RuntimeError("bend_edge: rotation failed")
    return xf.Shape()


def _fuse(a, b):
    from OCP.BRepAlgoAPI import BRepAlgoAPI_Fuse
    fuse = BRepAlgoAPI_Fuse(a, b)
    fuse.Build()
    if not fuse.IsDone():
        raise RuntimeError("bend_edge: BRepAlgoAPI_Fuse failed")
    return fuse.Shape()


def _build_bend_arc(
    bend_position: float,
    bend_axis_kind: Literal["X", "Y"],
    perp_min: float,
    perp_max: float,
    thickness: float,
    radius: float,
    angle_rad: float,
    *,
    invert_rotation: bool,
):
    """Build the toroidal sector connecting the keep and bent halves.

    The arc is built by revolving a flat rectangle (the cross-section of the
    sheet at the bend line) about the bend axis. The cross-section is a
    rectangle of size (edge_length x thickness) lying in the plane normal to
    the bend axis at position `bend_position` along the perpendicular axis.

    Args:
        bend_position: coordinate of the bend line on the perpendicular axis
            (the axis perpendicular to the bend axis, on the top face).
        bend_axis_kind: "X" or "Y" — direction of the bend axis (= edge dir).
        perp_min, perp_max: extents of the cross-section along the bend axis
            direction (i.e. the length of the bend line, in world coords).
        thickness: sheet thickness (z extent).
        radius: inner bend radius.
        angle_rad: positive bend angle (radians) — magnitude only.
        invert_rotation: if True, sense of rotation is reversed (e.g. bending
            the -X side rather than +X).

    Returns: OCCT TopoDS_Shape of the arc sector solid.
    """
    from OCP.BRepBuilderAPI import (
        BRepBuilderAPI_MakeFace,
        BRepBuilderAPI_MakePolygon,
    )
    from OCP.BRepPrimAPI import BRepPrimAPI_MakeRevol
    from OCP.gp import gp_Ax1, gp_Dir, gp_Pnt

    # Cross-section rectangle vertices. The rectangle is a planar quad in 3D.
    # For bend_axis_kind == "Y": the rectangle lies in the plane x=bend_position,
    # extends in y from perp_min..perp_max and in z from 0..thickness.
    # For bend_axis_kind == "X": rectangle in plane y=bend_position, extends in
    # x from perp_min..perp_max and in z from 0..thickness.
    if bend_axis_kind == "Y":
        p1 = gp_Pnt(bend_position, perp_min, 0.0)
        p2 = gp_Pnt(bend_position, perp_max, 0.0)
        p3 = gp_Pnt(bend_position, perp_max, thickness)
        p4 = gp_Pnt(bend_position, perp_min, thickness)
        # Bend axis: parallel to Y, at (bend_position, *, thickness + radius).
        axis_origin = (bend_position, 0.0, thickness + radius)
        axis_dir = (0.0, 1.0, 0.0)
    else:  # "X"
        p1 = gp_Pnt(perp_min, bend_position, 0.0)
        p2 = gp_Pnt(perp_max, bend_position, 0.0)
        p3 = gp_Pnt(perp_max, bend_position, thickness)
        p4 = gp_Pnt(perp_min, bend_position, thickness)
        axis_origin = (0.0, bend_position, thickness + radius)
        axis_dir = (1.0, 0.0, 0.0)

    poly = BRepBuilderAPI_MakePolygon(p1, p2, p3, p4, True)
    if not poly.IsDone():
        raise RuntimeError("bend_edge: cross-section polygon failed")
    wire = poly.Wire()
    face_maker = BRepBuilderAPI_MakeFace(wire, True)
    if not face_maker.IsDone():
        raise RuntimeError("bend_edge: cross-section face failed")
    face = face_maker.Face()

    # Revolve direction depends on which side is bent. Reverse axis direction
    # to flip the sense of rotation (BRepPrimAPI_MakeRevol takes a signed angle
    # but reversing the axis is more reliable).
    if invert_rotation:
        axis_dir = (-axis_dir[0], -axis_dir[1], -axis_dir[2])

    axis = gp_Ax1(gp_Pnt(*axis_origin), gp_Dir(*axis_dir))
    mk = BRepPrimAPI_MakeRevol(face, axis, angle_rad, True)
    if not mk.IsDone():
        raise RuntimeError("bend_edge: BRepPrimAPI_MakeRevol failed")
    return mk.Shape()


def _do_bend(
    shape,
    *,
    bend_axis_kind: Literal["X", "Y"],
    bend_position: float,
    bend_perp_min: float,
    bend_perp_max: float,
    bend_side: Literal["+X", "-X", "+Y", "-Y"],
    angle_deg: float,
    radius_mm: float,
):
    """Build the bent sheet from a flat sheet by constructing keep + arc +
    rotated bend pieces and fusing them.

    Returns the fused TopoDS_Shape.
    """
    xmin, ymin, zmin, xmax, ymax, zmax = _shape_bbox(shape)
    t = zmax - zmin
    if t <= 0:
        raise RuntimeError("bend_edge: input body has zero z-extent")

    # Bend axis runs along `bend_axis_kind`. The perpendicular axis on the
    # top face is the orthogonal in-plane axis.
    if bend_axis_kind == "Y":
        perp_axis = "X"
    else:
        perp_axis = "Y"

    # Validate bend_side matches the perpendicular axis.
    if bend_side[1] != perp_axis:
        raise RuntimeError(
            f"bend_edge: bend_side {bend_side} is not perpendicular to "
            f"bend axis {bend_axis_kind} (expected ±{perp_axis})"
        )
    side_sign = +1 if bend_side[0] == "+" else -1

    # Keep half = the side opposite of bend_side.
    # Bent half = the bend_side half (gets rotated).
    DEGEN_EPS = 1e-6
    if perp_axis == "X":
        if side_sign > 0:
            keep_corner = (xmin, ymin, zmin)
            keep_dx = bend_position - xmin
            keep_dy = ymax - ymin
            bent_corner = (bend_position, ymin, zmin)
            bent_dx = xmax - bend_position
            bent_dy = ymax - ymin
        else:
            keep_corner = (bend_position, ymin, zmin)
            keep_dx = xmax - bend_position
            keep_dy = ymax - ymin
            bent_corner = (xmin, ymin, zmin)
            bent_dx = bend_position - xmin
            bent_dy = ymax - ymin
    else:  # perp_axis == "Y"
        if side_sign > 0:
            keep_corner = (xmin, ymin, zmin)
            keep_dx = xmax - xmin
            keep_dy = bend_position - ymin
            bent_corner = (xmin, bend_position, zmin)
            bent_dx = xmax - xmin
            bent_dy = ymax - bend_position
        else:
            keep_corner = (xmin, bend_position, zmin)
            keep_dx = xmax - xmin
            keep_dy = ymax - bend_position
            bent_corner = (xmin, ymin, zmin)
            bent_dx = xmax - xmin
            bent_dy = bend_position - ymin

    if keep_dx <= DEGEN_EPS or keep_dy <= DEGEN_EPS:
        raise RuntimeError(
            "bend_edge: keep half has zero extent — bend_position falls on the "
            "body boundary on the keep side. Choose an interior bend_position."
        )
    if bent_dx <= DEGEN_EPS or bent_dy <= DEGEN_EPS:
        raise RuntimeError(
            "bend_edge: bent half has zero extent — bend_position falls on the "
            "body boundary on the bend side. Choose an interior bend_position."
        )
    keep = _make_box(keep_corner, keep_dx, keep_dy, t)
    bent = _make_box(bent_corner, bent_dx, bent_dy, t)

    # Build the arc connecting keep edge to bent piece.
    angle_rad = math.radians(abs(angle_deg))
    # The default rotation of BRepPrimAPI_MakeRevol about +Y by +φ sweeps
    # points at the cross-section x=bend_position into the -X half-space.
    # For a +X bend we need the arc to sweep into +X, so invert by default.
    # For a -X bend, no invert. For the X-axis case the same logic applies
    # in the orthogonal direction (sweep into +Y vs -Y) and the convention
    # matches: invert when side_sign>0 for axis_kind=Y, and the analogous
    # +Y bend for axis_kind=X also needs invert (BRepPrimAPI_MakeRevol about
    # +X by +φ sweeps +Y -> +Z; we want +Y to bend up to +Z, so default is
    # *correct*, i.e., do not invert for axis_kind=X, side_sign>0).
    if bend_axis_kind == "Y":
        invert = (side_sign > 0)
    else:
        invert = (side_sign < 0)
    if angle_deg < 0:
        invert = not invert

    arc = _build_bend_arc(
        bend_position=bend_position,
        bend_axis_kind=bend_axis_kind,
        perp_min=bend_perp_min,
        perp_max=bend_perp_max,
        thickness=t,
        radius=radius_mm,
        angle_rad=angle_rad,
        invert_rotation=invert,
    )

    # Rotate the bent piece about the bend axis. The rotation axis passes
    # through (bend_position, *, zmin + t + radius) along bend_axis_kind.
    if bend_axis_kind == "Y":
        axis_origin = (bend_position, 0.0, zmin + t + radius_mm)
        axis_dir = (0.0, 1.0, 0.0)
    else:
        axis_origin = (0.0, bend_position, zmin + t + radius_mm)
        axis_dir = (1.0, 0.0, 0.0)

    # Determine signed rotation angle. Right-hand rule about axis_dir:
    # for axis_dir = +Y, positive rotation takes +X -> -Z (i.e., +X half
    # would go *down*). We want +X half to go *up* (+Z) when angle_deg > 0
    # and bend_side = "+X". So apply a negative sign when side_sign>0 and
    # axis_dir matches the canonical bend axis. Empirically: rotation angle
    # for the bent piece is (-side_sign) * angle_deg for axis_dir = +Y, and
    # the matching signed value for axis_dir = +X works out to the same
    # negation. We bake this into a sign:
    signed_angle = -side_sign * math.radians(angle_deg)

    # For axis = +X (i.e. bend along X axis), the geometry is mirrored
    # relative to the +Y case. Right-hand rule with thumb +X: rotation
    # carries +Y -> +Z. So for bend_side = "+Y" with positive angle we want
    # +Y half to go up, which is +rotation about +X. The previous sign needs
    # to flip in that case.
    if bend_axis_kind == "X":
        signed_angle = -signed_angle

    bent_rotated = _rotate_shape(bent, axis_origin, axis_dir, signed_angle)

    # Fuse: keep + arc + bent_rotated. Boolean fuse may produce non-manifold
    # results if shells just touch; the toroidal arc is constructed to share
    # faces with both halves, so OCCT's fuse should knit them into one solid.
    fused1 = _fuse(keep, arc)
    fused2 = _fuse(fused1, bent_rotated)
    return fused2


@skill(
    name="bend_edge",
    category="modify/sheet",
    level="atomic",
    summary="Round bend of a flat sheet along a straight axis-aligned edge. "
            "One half is rotated about a bend axis offset by `radius_mm` above "
            "the top surface; the connecting region is a toroidal sector.",
    selector_kinds=["edges"],
    history_rules={
        "bent_edge":     HistoryRule.CONSUMED,
        "bend_arc_face": HistoryRule.GENERATED_NEW,
        "panel_faces":   HistoryRule.MODIFIED_INHERIT,
    },
    preconditions=[
        "pc.input_is_flat_sheet",
        "pc.edge_axis_aligned_on_top",
    ],
    produces_features=["bend"],
    preserves=["sheet_thickness"],
    manufacturing={
        "sheet_metal_stamp": {"min_fillet_r_mm": "args.radius_mm",
                              "extras": {"k_factor": 0.4}},
    },
    failure_modes=[
        "fm.edge_not_axis_aligned",
        "fm.radius_too_small",
        "fm.bend_side_mismatch",
    ],
    cost_hint=0.35,
    post_conditions=[PostCondition(kind="volume_changed", min_delta_mm3=0.5)],
)
class BendEdge(SkillBase):
    class Args(BaseModel):
        # One of {edge_selector, (bend_axis + bend_position_mm)} must be
        # supplied. edge_selector is the canonical form when the body has an
        # interior axis-aligned edge on its top face; bend_axis +
        # bend_position_mm is the explicit fallback for a plain sheet where
        # the bend line lies inside the rectangular footprint and there is
        # no resident edge to match.
        edge_selector: SelectorRef | None = None
        bend_axis: Literal["X", "Y"] | None = None
        bend_position_mm: float | None = None
        angle_deg: float = Field(ge=-180.0, le=180.0)
        radius_mm: float = Field(gt=0.0, le=200.0)
        bend_side: Literal["+X", "-X", "+Y", "-Y"]

    def _apply(self, body: Any, args: Args) -> SkillResult:
        from build123d import Part

        shape = body.wrapped if hasattr(body, "wrapped") else body

        if args.edge_selector is not None:
            edge = _resolve_bend_edge(shape, args.edge_selector)
            axis_kind, mid, length, endpoints = _edge_geom(edge)
            if axis_kind not in ("X", "Y"):
                raise RuntimeError(
                    f"bend_edge: edge must be parallel to X or Y axis on the "
                    f"top face, got axis={axis_kind}"
                )
            if axis_kind == "Y":
                bend_position = mid[0]
                (p1, p2) = endpoints
                perp_min = min(p1[1], p2[1])
                perp_max = max(p1[1], p2[1])
            else:
                bend_position = mid[1]
                (p1, p2) = endpoints
                perp_min = min(p1[0], p2[0])
                perp_max = max(p1[0], p2[0])
        elif args.bend_axis is not None and args.bend_position_mm is not None:
            axis_kind = args.bend_axis
            bend_position = args.bend_position_mm
            # Use the body's bbox in the edge direction as the bend line
            # extent.
            xmin, ymin, _, xmax, ymax, _ = _shape_bbox(shape)
            if axis_kind == "Y":
                perp_min, perp_max = ymin, ymax
            else:
                perp_min, perp_max = xmin, xmax
        else:
            raise RuntimeError(
                "bend_edge: must supply either edge_selector or "
                "(bend_axis + bend_position_mm)"
            )

        new_shape = _do_bend(
            shape,
            bend_axis_kind=axis_kind,
            bend_position=bend_position,
            bend_perp_min=perp_min,
            bend_perp_max=perp_max,
            bend_side=args.bend_side,
            angle_deg=args.angle_deg,
            radius_mm=args.radius_mm,
        )

        history = EntityHistoryMap(
            rules={
                "bent_edge":     HistoryRule.CONSUMED,
                "bend_arc_face": HistoryRule.GENERATED_NEW,
                "panel_faces":   HistoryRule.MODIFIED_INHERIT,
            },
        )
        return SkillResult(body=Part(new_shape), history=history)
