"""export_mesh_for_fem — atomic, read-only FEM/CAE bridge.

Tesselate the body with ``BRepMesh_IncrementalMesh`` and write the surface
triangulation in one of three formats consumable by external solvers:

  * ``inp`` — Abaqus / Calculix keyword deck. ``*NODE`` block with node
    coordinates and ``*ELEMENT, TYPE=S3`` block with 3-noded triangular
    shell elements. Sufficient as a starting point for thin-shell FEA;
    users typically convert to tets in their solver.
  * ``msh`` — Gmsh ASCII v2.2 (``$MeshFormat 2.2 0 8``). Nodes block and
    elements block with element type 2 (3-node triangle).
  * ``stl`` — binary STL via ``StlAPI_Writer`` (a convenience pass-through
    so callers that already chose the FEM family can still emit STL).

The skill is read-only — the body is returned unchanged and only the
filesystem is touched.

extras["mesh_stats"] schema:
    {"tris": int, "nodes": int, "path": str, "format": str,
     "deflection_mm": float}
"""
from __future__ import annotations

import math
import struct
from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel, Field

from phone_designer.skills._history import EntityHistoryMap
from phone_designer.skills._post_conditions import PostCondition
from phone_designer.skills._registry import skill
from phone_designer.skills._spec import SkillBase, SkillResult


def _occt_shape(body: Any):
    return body.wrapped if hasattr(body, "wrapped") else body


def _collect_triangles(shape) -> tuple[list[tuple[float, float, float]],
                                        list[tuple[int, int, int]]]:
    """Walk every face, transform its triangulation by the face Location, and
    return a flat (nodes, triangles) pair with 1-based-friendly 0-based indices.

    Nodes are de-duplicated to a precision of ~1e-6 mm so that adjacent faces
    share corner vertices (important for FEM connectivity)."""
    from OCP.BRep import BRep_Tool
    from OCP.TopAbs import TopAbs_FACE
    from OCP.TopExp import TopExp_Explorer
    from OCP.TopLoc import TopLoc_Location
    from OCP.TopoDS import TopoDS

    nodes: list[tuple[float, float, float]] = []
    node_lookup: dict[tuple[int, int, int], int] = {}
    tris: list[tuple[int, int, int]] = []

    def _key(x: float, y: float, z: float) -> tuple[int, int, int]:
        # 1e-6 mm bucket (1 nm) — plenty for geometric matching, cheap to hash.
        return (int(round(x * 1e6)), int(round(y * 1e6)), int(round(z * 1e6)))

    def _add_node(x: float, y: float, z: float) -> int:
        k = _key(x, y, z)
        idx = node_lookup.get(k)
        if idx is None:
            idx = len(nodes)
            node_lookup[k] = idx
            nodes.append((x, y, z))
        return idx

    it = TopExp_Explorer(shape, TopAbs_FACE)
    while it.More():
        try:
            face = TopoDS.Face_s(it.Current())
        except Exception:
            it.Next()
            continue
        loc = TopLoc_Location()
        try:
            tri = BRep_Tool.Triangulation_s(face, loc)
        except Exception:
            tri = None
        if tri is None:
            it.Next()
            continue
        trsf = loc.Transformation()
        n_nb = int(tri.NbNodes())
        # Map face-local 1-based node id → global de-duped index.
        local_to_global: dict[int, int] = {}
        for i in range(1, n_nb + 1):
            try:
                p = tri.Node(i).Transformed(trsf)
                gi = _add_node(p.X(), p.Y(), p.Z())
                local_to_global[i] = gi
            except Exception:
                continue
        t_nb = int(tri.NbTriangles())
        # Detect orientation reversal — flip winding to keep outward normals.
        from OCP.TopAbs import TopAbs_REVERSED
        reversed_ = (face.Orientation() == TopAbs_REVERSED)
        for j in range(1, t_nb + 1):
            try:
                tj = tri.Triangle(j)
                a, b, c = tj.Get()
            except Exception:
                continue
            ga = local_to_global.get(a)
            gb = local_to_global.get(b)
            gc = local_to_global.get(c)
            if ga is None or gb is None or gc is None:
                continue
            if reversed_:
                tris.append((ga, gc, gb))
            else:
                tris.append((ga, gb, gc))
        it.Next()

    return nodes, tris


def _write_inp(path: Path, nodes: list[tuple[float, float, float]],
                tris: list[tuple[int, int, int]]) -> None:
    """Abaqus / Calculix INP keyword deck. Nodes are 1-based."""
    lines: list[str] = []
    lines.append("*HEADING")
    lines.append("Generated by phone_designer.skills.fem_cae.export_mesh_for_fem")
    lines.append("*NODE")
    for i, (x, y, z) in enumerate(nodes, start=1):
        lines.append(f"{i}, {x:.6f}, {y:.6f}, {z:.6f}")
    lines.append("*ELEMENT, TYPE=S3, ELSET=SURFACE")
    for j, (a, b, c) in enumerate(tris, start=1):
        # +1 to make 1-based.
        lines.append(f"{j}, {a + 1}, {b + 1}, {c + 1}")
    lines.append("*END PART")
    path.write_text("\n".join(lines) + "\n", encoding="ascii")


def _write_msh(path: Path, nodes: list[tuple[float, float, float]],
                tris: list[tuple[int, int, int]]) -> None:
    """Gmsh ASCII v2.2 file."""
    lines: list[str] = []
    lines.append("$MeshFormat")
    lines.append("2.2 0 8")
    lines.append("$EndMeshFormat")
    lines.append("$Nodes")
    lines.append(str(len(nodes)))
    for i, (x, y, z) in enumerate(nodes, start=1):
        lines.append(f"{i} {x:.6f} {y:.6f} {z:.6f}")
    lines.append("$EndNodes")
    lines.append("$Elements")
    lines.append(str(len(tris)))
    # element-type 2 = 3-node triangle; 2 tags (physical, geometrical) both 0.
    for j, (a, b, c) in enumerate(tris, start=1):
        lines.append(f"{j} 2 2 0 0 {a + 1} {b + 1} {c + 1}")
    lines.append("$EndElements")
    path.write_text("\n".join(lines) + "\n", encoding="ascii")


def _write_stl_via_occt(shape, path: Path) -> None:
    """Fall back to OCCT's StlAPI_Writer for STL output."""
    from OCP.StlAPI import StlAPI_Writer
    writer = StlAPI_Writer()
    ok = writer.Write(shape, str(path))
    if not ok or not path.exists():
        raise RuntimeError(f"export_mesh_for_fem: StlAPI_Writer failed → {path}")


def _write_stl_binary(path: Path, nodes: list[tuple[float, float, float]],
                       tris: list[tuple[int, int, int]]) -> None:
    """Backup binary STL writer used if OCCT path is unavailable."""
    header = b"phone_designer.fem_cae" + b"\x00" * (80 - 22)
    with path.open("wb") as f:
        f.write(header)
        f.write(struct.pack("<I", len(tris)))
        for (ai, bi, ci) in tris:
            ax, ay, az = nodes[ai]
            bx, by, bz = nodes[bi]
            cx, cy, cz = nodes[ci]
            # Compute outward normal.
            ux, uy, uz = bx - ax, by - ay, bz - az
            vx, vy, vz = cx - ax, cy - ay, cz - az
            nx = uy * vz - uz * vy
            ny = uz * vx - ux * vz
            nz = ux * vy - uy * vx
            mag = math.sqrt(nx * nx + ny * ny + nz * nz)
            if mag > 1e-12:
                nx, ny, nz = nx / mag, ny / mag, nz / mag
            f.write(struct.pack("<3f", nx, ny, nz))
            f.write(struct.pack("<3f", ax, ay, az))
            f.write(struct.pack("<3f", bx, by, bz))
            f.write(struct.pack("<3f", cx, cy, cz))
            f.write(struct.pack("<H", 0))


@skill(
    name="export_mesh_for_fem",
    category="fem_cae",
    level="atomic",
    summary="Tesselate the body via BRepMesh_IncrementalMesh and write the "
            "surface mesh as Abaqus INP, Gmsh MSH, or STL. Read-only — body "
            "unchanged; only the filesystem is touched.",
    selector_kinds=[],
    history_rules={},
    produces_features=["fem_mesh_artifact"],
    preserves=["body_topology"],
    manufacturing={},
    failure_modes=["fm.tessellation_failed", "fm.mesh_write_failed"],
    cost_hint=0.2,
    post_conditions=[PostCondition(kind="body_present")],
)
class ExportMeshForFem(SkillBase):
    class Args(BaseModel):
        out_path: str = Field(min_length=1)
        deflection_mm: float = Field(default=0.05, gt=0.0, le=10.0)
        format: Literal["inp", "msh", "stl"] = "inp"

    def _apply(self, body: Any, args: Args) -> SkillResult:
        from OCP.BRepMesh import BRepMesh_IncrementalMesh

        if body is None:
            raise ValueError("export_mesh_for_fem: body is None")

        shape = _occt_shape(body)
        if shape is None:
            raise ValueError("export_mesh_for_fem: body.wrapped is None")

        # Tesselate in-place. angular_deflection defaults to ~5° (0.0873 rad).
        mesher = BRepMesh_IncrementalMesh(
            shape,
            float(args.deflection_mm),
            False,
            math.radians(5.0),
            True,
        )
        mesher.Perform()
        if not mesher.IsDone():
            raise RuntimeError(
                "export_mesh_for_fem: BRepMesh_IncrementalMesh failed",
            )

        out = Path(args.out_path)
        out.parent.mkdir(parents=True, exist_ok=True)

        nodes, tris = _collect_triangles(shape)
        if len(tris) == 0:
            raise RuntimeError(
                "export_mesh_for_fem: 0 triangles after tessellation — "
                "deflection too coarse or shape empty",
            )

        fmt = args.format
        if fmt == "inp":
            _write_inp(out, nodes, tris)
        elif fmt == "msh":
            _write_msh(out, nodes, tris)
        elif fmt == "stl":
            try:
                _write_stl_via_occt(shape, out)
            except Exception:
                _write_stl_binary(out, nodes, tris)
        else:
            raise ValueError(f"export_mesh_for_fem: unknown format {fmt!r}")

        if not out.exists():
            raise RuntimeError(
                f"export_mesh_for_fem: writer claimed success but file missing → {out}",
            )

        stats = {
            "tris": int(len(tris)),
            "nodes": int(len(nodes)),
            "path": str(out),
            "format": fmt,
            "deflection_mm": float(args.deflection_mm),
        }
        return SkillResult(
            body=body,
            history=EntityHistoryMap(),
            extras={"mesh_stats": stats},
        )
