"""export_abaqus_inp_v2 — atomic, read-only Abaqus INP exporter (v2).

A richer version of ``export_mesh_for_fem`` that consumes the full set of
body annotations attached by the other ``fem_cae`` skills:

  * body._pd_material        → ``*MATERIAL`` + ``*ELASTIC`` + ``*DENSITY``
  * body._pd_bcs             → ``*BOUNDARY`` (fixed/pinned) and ``*DLOAD`` /
                               ``*DSLOAD`` (pressure/force/temperature)
  * body._pd_thermal_bcs     → ``*BOUNDARY`` (fixed_temp) / ``*DFLUX`` /
                               ``*FILM`` / ``*SRADIATE``
  * body._pd_contacts        → ``*SURFACE`` + ``*CONTACT PAIR``
  * body._pd_load_cases      → one ``*STEP`` per case
  * body._pd_modal           → ``*FREQUENCY`` inside a modal step
  * body._pd_mesh_refinement → recorded as a comment block (the actual
                               per-zone meshing is left to the solver's
                               adaptive remesher)

The geometric surface mesh is generated by the same triangulation pipeline
as ``export_mesh_for_fem`` — we import that module's helpers so the two
exporters stay in sync.

Read-only — the body is returned unchanged; only the filesystem is touched.

extras["mesh_stats"]:
    {"tris": int, "nodes": int, "path": str, "format": "inp_v2",
     "mesh_size_mm": float, "bc_cards": int, "contact_cards": int,
     "load_case_steps": int}
"""
from __future__ import annotations

import math
from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field

from phone_designer.skills._history import EntityHistoryMap
from phone_designer.skills._post_conditions import PostCondition
from phone_designer.skills._registry import skill
from phone_designer.skills._spec import SkillBase, SkillResult
from phone_designer.skills.fem_cae.boundary_condition_tag import get_bcs
from phone_designer.skills.fem_cae.contact_pair import get_contacts
from phone_designer.skills.fem_cae.export_mesh_for_fem import (
    _collect_triangles,
    _occt_shape,
)
from phone_designer.skills.fem_cae.load_case_compose import get_load_cases
from phone_designer.skills.fem_cae.material_property_tag import get_material
from phone_designer.skills.fem_cae.mesh_refinement_zones import (
    get_mesh_refinement,
)
from phone_designer.skills.fem_cae.modal_analysis_setup import get_modal
from phone_designer.skills.fem_cae.thermal_bc_tag import get_thermal_bcs


# ────────────────────────────────────────────────────────────────────────────
# Helpers — face-center → 1-based node id lookup so BC cards can refer to
# specific nodes / element-sets even though we only know face centroids.


def _nearest_node(centers_xyz: list[tuple[float, float, float]],
                   nodes: list[tuple[float, float, float]]) -> list[int]:
    """For each query centroid return the 1-based node id of the closest
    triangulation node. Brute-force — O(C·N), fine for shells up to ~10⁵ nodes.
    """
    out: list[int] = []
    for cx, cy, cz in centers_xyz:
        best_i = 1
        best_d = float("inf")
        for i, (x, y, z) in enumerate(nodes, start=1):
            dx, dy, dz = x - cx, y - cy, z - cz
            d = dx * dx + dy * dy + dz * dz
            if d < best_d:
                best_d = d
                best_i = i
        out.append(best_i)
    return out


def _bc_to_cards(bc: dict[str, Any],
                  nodes: list[tuple[float, float, float]],
                  nset_index: int) -> tuple[list[str], int]:
    """Convert a single _pd_bcs record to a list of INP card lines.

    Returns (lines, number_of_cards). The skill emits ``*NSET`` for the
    matched centroids and then a ``*BOUNDARY`` or ``*DLOAD`` referencing it.
    """
    lines: list[str] = []
    centers = bc.get("face_centers", [])
    if not centers:
        return [], 0
    node_ids = _nearest_node(centers, nodes)
    nset_name = f"NSET_BC_{nset_index}"
    lines.append(f"*NSET, NSET={nset_name}")
    # 1 node per line is the simplest legal form — chunk for readability.
    lines.extend(f"{nid}," for nid in node_ids)
    kind = bc.get("kind")
    val = bc.get("value")
    if kind == "fixed":
        # Encastre — DOFs 1..6.
        lines.append("*BOUNDARY")
        lines.append(f"{nset_name}, 1, 6")
        return lines, 1
    if kind == "pinned":
        # Translation locked, rotation free — DOFs 1..3.
        lines.append("*BOUNDARY")
        lines.append(f"{nset_name}, 1, 3")
        return lines, 1
    if kind == "force":
        if not isinstance(val, (list, tuple)) or len(val) != 3:
            return lines, 0
        # CLOAD per direction, applied to each node in the NSET.
        lines.append("*CLOAD")
        for i, comp in enumerate(val, start=1):
            if abs(float(comp)) < 1e-12:
                continue
            lines.append(f"{nset_name}, {i}, {float(comp):.6f}")
        return lines, 1
    if kind == "pressure":
        # No element surface known here — emit as a comment so the user
        # can review. The full DSLOAD path needs *SURFACE definition
        # tied to elements, which is out of scope for the centroid-based
        # mapping.
        lines.append(f"*DLOAD, OP=NEW")
        # PRESS magnitude on a phantom surface name derived from nset.
        lines.append(f"** pressure {float(val):.6f} MPa on faces ~ {nset_name}")
        return lines, 1
    if kind == "temperature":
        lines.append("*BOUNDARY")
        lines.append(f"{nset_name}, 11, 11, {float(val):.6f}")
        return lines, 1
    return lines, 0


def _thermal_bc_to_cards(bc: dict[str, Any],
                          nodes: list[tuple[float, float, float]],
                          nset_index: int) -> tuple[list[str], int]:
    """Convert a _pd_thermal_bcs record to INP cards."""
    lines: list[str] = []
    centers = bc.get("face_centers", [])
    if not centers:
        return [], 0
    node_ids = _nearest_node(centers, nodes)
    nset_name = f"NSET_TBC_{nset_index}"
    lines.append(f"*NSET, NSET={nset_name}")
    lines.extend(f"{nid}," for nid in node_ids)
    kind = bc.get("kind")
    val = bc.get("value", 0.0)
    if kind == "fixed_temp":
        lines.append("*BOUNDARY")
        lines.append(f"{nset_name}, 11, 11, {float(val):.6f}")
        return lines, 1
    if kind == "heat_flux":
        lines.append(f"** heat_flux {float(val):.6f} W/m^2 on {nset_name}")
        lines.append("*CFLUX")
        for nid in node_ids:
            lines.append(f"{nid}, 11, {float(val):.6f}")
        return lines, 1
    if kind == "convection":
        h = bc.get("h_coefficient") or 0.0
        ta = bc.get("ambient_t_c") or 0.0
        lines.append(f"** convection h={float(h):.6f}, T_amb={float(ta):.6f}")
        lines.append("*FILM")
        for nid in node_ids:
            lines.append(f"{nid}, F11, {float(ta):.6f}, {float(h):.6f}")
        return lines, 1
    if kind == "radiation":
        eps = float(val)
        ta = bc.get("ambient_t_c") or 0.0
        lines.append(f"** radiation eps={eps:.6f}, T_amb={float(ta):.6f}")
        lines.append("*SRADIATE")
        for nid in node_ids:
            lines.append(f"{nid}, R11, {float(ta):.6f}, {eps:.6f}")
        return lines, 1
    return lines, 0


def _contact_to_cards(pair: dict[str, Any],
                       nodes: list[tuple[float, float, float]],
                       index: int) -> tuple[list[str], int]:
    """Convert a _pd_contacts record to INP cards (NSETs + *CONTACT PAIR)."""
    lines: list[str] = []
    a_ctr = pair.get("a_face_centers", [])
    b_ctr = pair.get("b_face_centers", [])
    if not a_ctr or not b_ctr:
        return [], 0
    a_ids = _nearest_node(a_ctr, nodes)
    b_ids = _nearest_node(b_ctr, nodes)
    name_a = f"CSURF_A_{index}"
    name_b = f"CSURF_B_{index}"
    lines.append(f"*NSET, NSET={name_a}")
    lines.extend(f"{nid}," for nid in a_ids)
    lines.append(f"*NSET, NSET={name_b}")
    lines.extend(f"{nid}," for nid in b_ids)
    # Surface-on-NSET, NODE type.
    lines.append(f"*SURFACE, NAME={name_a}_S, TYPE=NODE")
    lines.append(f"{name_a},")
    lines.append(f"*SURFACE, NAME={name_b}_S, TYPE=NODE")
    lines.append(f"{name_b},")
    kind = pair.get("kind", "frictionless")
    mu = pair.get("friction_coef")
    interaction_name = f"CINT_{index}"
    lines.append(f"*SURFACE INTERACTION, NAME={interaction_name}")
    if kind == "frictional" and mu is not None:
        lines.append("*FRICTION")
        lines.append(f"{float(mu):.6f},")
    elif kind == "rough":
        lines.append("*FRICTION, ROUGH")
    elif kind == "bonded":
        lines.append("*TIE")
        lines.append(f"{name_a}_S, {name_b}_S")
    # No extra block for frictionless — default μ=0.
    if kind != "bonded":
        lines.append(f"*CONTACT PAIR, INTERACTION={interaction_name}")
        lines.append(f"{name_a}_S, {name_b}_S")
    return lines, 1


def _material_cards(mat: dict[str, Any]) -> list[str]:
    """Convert _pd_material → ``*MATERIAL`` / ``*ELASTIC`` / ``*DENSITY``."""
    lines: list[str] = []
    name = "MAT_BODY"
    lines.append(f"*MATERIAL, NAME={name}")
    lines.append("*ELASTIC")
    lines.append(
        f"{float(mat.get('youngs_modulus_mpa', 200000.0)):.6f}, "
        f"{float(mat.get('poisson', 0.3)):.6f}"
    )
    lines.append("*DENSITY")
    # INP density wants tonne/mm³ if length units are mm — convert kg/m³.
    rho_kg_m3 = float(mat.get("density_kg_m3", 7850.0))
    rho_tonne_mm3 = rho_kg_m3 * 1.0e-12
    lines.append(f"{rho_tonne_mm3:.6e},")
    # Yield as a comment for downstream tooling.
    lines.append(f"** yield_mpa: {float(mat.get('yield_mpa', 0.0)):.6f}")
    return lines


def _step_cards(case: dict[str, Any], modal: dict[str, Any] | None) -> list[str]:
    """Emit a single ``*STEP`` block for one load case."""
    lines: list[str] = []
    name = case.get("name", "STEP")
    analysis = case.get("analysis_type", "static")
    lines.append(f"*STEP, NAME={name}")
    if analysis == "static":
        lines.append("*STATIC")
        lines.append("1.0, 1.0,")
    elif analysis == "modal":
        lines.append("*FREQUENCY")
        if modal is not None:
            count = int(modal.get("count", 10))
            lo, hi = modal.get("range", (0.0, 1000.0))
            lines.append(f"{count}, {float(lo):.6f}, {float(hi):.6f}")
        else:
            lines.append("10, , ,")
    elif analysis == "thermal":
        lines.append("*HEAT TRANSFER, STEADY STATE")
        lines.append("1.0, 1.0,")
    elif analysis == "transient":
        lines.append("*DYNAMIC")
        lines.append("0.01, 1.0,")
    # Embedded loads (free-form dicts) — emit as comments.
    for ld in case.get("loads", []):
        lines.append(f"** load: {ld}")
    # Reference BCs by name as comments — the actual cards are emitted
    # outside the step in the global section.
    for bc_name in case.get("bcs", []):
        lines.append(f"** uses BC: {bc_name}")
    lines.append("*END STEP")
    return lines


def _write_inp_v2(
    path: Path,
    nodes: list[tuple[float, float, float]],
    tris: list[tuple[int, int, int]],
    *,
    body: Any,
    include_bcs: bool,
    include_loads: bool,
    include_contacts: bool,
    mesh_size_mm: float,
) -> dict[str, int]:
    """Write the full INP v2 deck. Returns counts for stats."""
    lines: list[str] = []
    lines.append("*HEADING")
    lines.append(
        "Generated by phone_designer.skills.fem_cae.export_abaqus_inp_v2"
    )
    lines.append(f"** mesh_size_mm: {mesh_size_mm:.6f}")

    # Mesh refinement zones — comment block (Abaqus does not have a single
    # keyword for per-region adaptive sizing in the global deck).
    refines = get_mesh_refinement(body)
    if refines:
        lines.append("** mesh refinement zones:")
        for i, zone in enumerate(refines, start=1):
            lines.append(
                f"**   zone {i}: factor={zone.get('factor')}, "
                f"n_faces={len(zone.get('face_centers', []))}"
            )

    # Nodes.
    lines.append("*NODE")
    for i, (x, y, z) in enumerate(nodes, start=1):
        lines.append(f"{i}, {x:.6f}, {y:.6f}, {z:.6f}")
    # Elements.
    lines.append("*ELEMENT, TYPE=S3, ELSET=SURFACE")
    for j, (a, b, c) in enumerate(tris, start=1):
        lines.append(f"{j}, {a + 1}, {b + 1}, {c + 1}")

    # Material.
    mat = get_material(body)
    if mat is not None:
        lines.extend(_material_cards(mat))
        # Section assignment — single shell section on SURFACE.
        lines.append("*SHELL SECTION, ELSET=SURFACE, MATERIAL=MAT_BODY")
        lines.append("1.0,")

    bc_cards = 0
    contact_cards = 0
    load_case_steps = 0

    # Mechanical BCs (global section before any *STEP).
    if include_bcs:
        for i, bc in enumerate(get_bcs(body), start=1):
            block, n = _bc_to_cards(bc, nodes, nset_index=i)
            lines.extend(block)
            bc_cards += n
        # Thermal BCs.
        for i, bc in enumerate(get_thermal_bcs(body), start=1):
            block, n = _thermal_bc_to_cards(bc, nodes, nset_index=i)
            lines.extend(block)
            bc_cards += n

    if include_contacts:
        for i, pair in enumerate(get_contacts(body), start=1):
            block, n = _contact_to_cards(pair, nodes, index=i)
            lines.extend(block)
            contact_cards += n

    if include_loads:
        cases = get_load_cases(body)
        modal = get_modal(body)
        for case in cases:
            lines.extend(_step_cards(case, modal))
            load_case_steps += 1
        # If no cases were declared but a modal setup exists, emit a default
        # frequency step so the deck is usable.
        if not cases and modal is not None:
            lines.extend(_step_cards(
                {"name": "MODAL_DEFAULT", "analysis_type": "modal"}, modal,
            ))
            load_case_steps += 1

    # Abaqus INP decks are conventionally ASCII; fall back to replacing any
    # stray non-ASCII glyphs (e.g. units like "²") with "?" rather than
    # crashing the writer.
    path.write_text(
        "\n".join(lines) + "\n", encoding="ascii", errors="replace",
    )
    return {
        "bc_cards":        bc_cards,
        "contact_cards":   contact_cards,
        "load_case_steps": load_case_steps,
    }


@skill(
    name="export_abaqus_inp_v2",
    category="fem_cae",
    level="atomic",
    summary="Write an Abaqus / Calculix INP deck containing the surface mesh "
            "plus *MATERIAL, *BOUNDARY, *DLOAD / *CLOAD, *CONTACT PAIR, "
            "*FREQUENCY, and one *STEP per registered load case. Reuses the "
            "tessellation pipeline of export_mesh_for_fem and consumes the "
            "tags attached by the other fem_cae skills. Read-only — body "
            "unchanged.",
    selector_kinds=[],
    history_rules={},
    produces_features=["fem_mesh_artifact", "fem_inp_v2"],
    preserves=["body_topology"],
    manufacturing={},
    failure_modes=["fm.tessellation_failed", "fm.mesh_write_failed"],
    cost_hint=0.25,
    post_conditions=[PostCondition(kind="body_present")],
)
class ExportAbaqusInpV2(SkillBase):
    class Args(BaseModel):
        path: str = Field(min_length=1)
        include_bcs: bool = True
        include_loads: bool = True
        include_contacts: bool = True
        mesh_size_mm: float = Field(default=2.0, gt=0.0, le=100.0)

    def _apply(self, body: Any, args: Args) -> SkillResult:
        from OCP.BRepMesh import BRepMesh_IncrementalMesh

        if body is None:
            raise ValueError("export_abaqus_inp_v2: body is None")
        shape = _occt_shape(body)
        if shape is None:
            raise ValueError("export_abaqus_inp_v2: body.wrapped is None")

        # Use mesh_size_mm as the linear deflection. This is a coarse
        # approximation — Abaqus will refine via its own remesher anyway.
        mesher = BRepMesh_IncrementalMesh(
            shape,
            float(args.mesh_size_mm),
            False,
            math.radians(5.0),
            True,
        )
        mesher.Perform()
        if not mesher.IsDone():
            raise RuntimeError(
                "export_abaqus_inp_v2: BRepMesh_IncrementalMesh failed",
            )

        out = Path(args.path)
        out.parent.mkdir(parents=True, exist_ok=True)
        nodes, tris = _collect_triangles(shape)
        if not tris:
            raise RuntimeError(
                "export_abaqus_inp_v2: 0 triangles after tessellation — "
                "mesh_size_mm too coarse or shape empty",
            )

        counts = _write_inp_v2(
            out, nodes, tris,
            body=body,
            include_bcs=args.include_bcs,
            include_loads=args.include_loads,
            include_contacts=args.include_contacts,
            mesh_size_mm=float(args.mesh_size_mm),
        )
        if not out.exists():
            raise RuntimeError(
                f"export_abaqus_inp_v2: writer claimed success but file missing → {out}",
            )

        stats = {
            "tris":            int(len(tris)),
            "nodes":           int(len(nodes)),
            "path":            str(out),
            "format":          "inp_v2",
            "mesh_size_mm":    float(args.mesh_size_mm),
            "bc_cards":        int(counts["bc_cards"]),
            "contact_cards":   int(counts["contact_cards"]),
            "load_case_steps": int(counts["load_case_steps"]),
        }
        return SkillResult(
            body=body,
            history=EntityHistoryMap(),
            extras={"mesh_stats": stats},
        )
